service: cat-rekognation

frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs14.x

  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:ListBucket
        - s3:GetObject
        - s3:DeleteObject
      Resource: arn:aws:s3:::cat-rekognation/*
    - Effect: Allow
      Action: 
        - rekognition:DetectLabels
      Resource: "*"

functions:
  validateImage:
    handler: handler.validateImage
    events:
      - s3:
          bucket: cat-rekognation
          event: s3:ObjectCreated:*
    destinations:
      onSuccess: arn:aws:sns:us-east-1:247513377090:success
